%
% Script to pull out the key parameters used for the simulator run
%

clear

dirname = './';
prefix = '2Mar09_'


fprintf(['Loading ', prefix,' ... \n'])

eval(['load ',dirname, prefix,'sim']);

eval(['load ',dirname, 'tmid']); % will be deleted once this is re-run

H2O_reflectivity = 0.63;

%
% Parameters for the numerical integration:
%
thetastep  = mp.thetastep/cp.Ti;  % rad
Doppstep = mp.dftilde;   % Hz.
Doppmax = mp.ftilde_max; % Hz.
delaystep = mp.acfmodel.delaystep;  % m
%nwf = number of coherent waveforms generated in each sample
nic % number of samples generated in each ensemble. 
hist_ensemble = size(wfnsyn,1);

fprintf('Simulation parameters: \n');
fprintf('    Azimuth (theta) step %10.4f rad. \n',thetastep);
fprintf('    Doppler (f-tilde) step %10.4f Hz. \n', Doppstep);
fprintf('    Doppler  (f-tilde) max (set) %10.4f Hz. \n', Doppmax);
fprintf('    Doppler  (f-tilde) max %10.4f Hz. \n', min(ftilde));
fprintf('    Doppler  (f-tilde) max %10.4f Hz. \n', max(ftilde));
fprintf('    Delay step %10.4f rad. \n',delaystep);
fprintf('    Incoherent average of %7i waveforms \n', nwf);
fprintf('    Simulation ensemble of %7i waveforms \n', nic);
fprintf('    Histograms generated using ensemble of %7i waveforms \n', hist_ensemble);

%
% Parameters for each case
%
%
% Hardcoded for 4 cases
%

fprintf('Parameters for each (4) cases : \n');

CN0dB = 10*log10(CN0/H2O_reflectivity);  % CN0 was generated by fit of waveform statsitics -
                                         %  reported here is the CN0 from
                                         %  the incident radiation.
                                      
fprintf('    PRN: %4i & %4i & %4i & %4i  \n', prnhist)
fprintf('    Time (GPS ?): %10.2f & %10.2f & %10.2f & %10.2f  (Hz) \n',t_pol(select));
fprintf('    C/N0: %10.1f & %10.1f & %10.1f & %10.1f  (dB-Hz) \n',CN0dB);
fprintf('    SV Elevation: %10.1f & %10.1f & %10.1f & %10.1f  (deg) \n',elhist); 
fprintf('    SV Azimuth : %10.1f & %10.1f & %10.1f & %10.1f  (deg) \n', azhist); 
fprintf('    Aircraft Altitude : %10.0f & %10.0f & %10.0f & %10.0f  (m) \n', althist);
fprintf('    Aircraft Velocity (x) : %10.1f & %10.1f & %10.1f & %10.1f  (m/s) \n', VRscat(:,1));
fprintf('    Aircraft Velocity (y) : %10.1f & %10.1f & %10.1f & %10.1f  (m/s) \n', VRscat(:,2));
fprintf('    Aircraft Velocity (z) : %10.1f & %10.1f & %10.1f & %10.1f  (m/s) \n', VRscat(:,3));
fprintf('    SV Velocity (x) : %10.1f & %10.1f & %10.1f & %10.1f  (m/s) \n', VGscat(:,1));
fprintf('    SV Velocity (y) : %10.1f & %10.1f & %10.1f & %10.1f  (m/s) \n', VGscat(:,2));
fprintf('    SV Velocity (z) : %10.1f & %10.1f & %10.1f & %10.1f  (m/s) \n', VGscat(:,3));
fprintf('    POLSCAT winds : %6.1f & %6.1f & %6.1f & %6.1f  (m/s) \n', wpol(select));
fprintf('    PALS T_{bv} : %6.1f & %6.1f & %6.1f & %6.1f  (m/s) \n', tbv(select));
fprintf('    MSS : %5.3f & %5.3f & %5.3f & %5.3f  (m/s) \n', xest(:,1));


